stages:
- name: package
  steps:
  - runScriptConfig:
      image: registry.cn-hangzhou.aliyuncs.com/liuwenzhong/maven3
      shellScript: mvn clean install
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      tag: spring-boot-docker
      registry: 127.0.0.1:34313
- name: fabu
  steps:
  - applyAppConfig:
      catalogTemplate: spring-boot
      version: spring-boot
      name: spring-boot-docker
      targetNamespace: nginx
timeout: 60
notification: {}
